# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_CONFIG_VERSION = "2"

Vagrant.configure(VAGRANT_CONFIG_VERSION) do |config|
  config.vm.box = "generic/ubuntu1804"

  # Main application folder
  config.vm.synced_folder "../..", "/vagrant"
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "util/sharpfuzz/playbook.yml"
  end

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "8" # We're using this for fuzzing, a lot of CPU is beneficial
  end
end
